### ISSUE TITLE
[UX] Matoucí buttony?

### ISSUE THREAD

**Issue by janpeterka** [tomas-dostal/potrebujurousku#16]
## Problém

![Screenshot from 2020-10-24 20-30-00](https://user-images.githubusercontent.com/6343648/97090380-dc4d5500-1637-11eb-9054-66cac883666b.png)
Ty buttony jsou pro mě matoucí - čekal bych, že když na ně kliknu (zobrazují se jako kliknutelné), tak to něco udělá - pravděpodobně vyfiltruje typ opatření.

## Návrh řešení
Buď bych změnil, aby se na to **nedalo kliknout** (možná přes disabled, nebo z toho udělat `span`, který má ty classes?).
Nebo bych tam přidal to filtrování (nevím ale, jestli je to funkce, kterou by někdo chtěl využít)

**Comment by tomas-dostal** [comment]
Nebo k tomu možná přidělat nějaké vyskakovací okna, které by to vyvolávalo, ať se to chová úplně jako tlačítka opatření, které tam jsou všude pod touhle "legendou"... Ani nastavení těch tlačítek na disabled by nemusel být špatný nápad...

**Comment by tomas-dostal** [comment]
Jde tam přidat class ``` disabled ``` , ale i tak jdou ty prvky vybrat, dá se přes ně projíždět tabulátorem, takže to nemá jiný efekt, než že se to zbarví jinak... 

![Screenshot from 2020-10-26 01-51-03](https://user-images.githubusercontent.com/29264497/97123876-14cf5a80-172e-11eb-8dec-edb58935b318.png)
