### ISSUE TITLE
Pushování do masteru

### ISSUE THREAD

**Issue by janmpeterka** [tomas-dostal/potrebujurousku#20]
@tomas-dostal Ve [FAQ](https://github.com/tomas-dostal/potrebujurousku/blob/master/dev_FAQ.md) píšeš, že se nemá pushovat do masteru. V nastavení repozitáře se to dá i úplně zakázat, tak bych byl pro, abys to udělal.

Možná tam jde i nastavit, abys třeba ty mohl, ale nejsem si tím jistý. Zároveň je to možná zbytečné - i když chceš udělat hotfix, tak se dá vytvořit PR a hned ho mergnout, není to o tolik víc práce :)

**Comment by tomas-dostal** [comment]
Snad už vyřešeno. Budu s tím asi chvilku bojovat, protože přímo do masteru jsem pushoval stejně jenom já, ale z dlouhodobého hlediska super tip. Dík!
