### ISSUE TITLE
Migrace databáze, přepis do ORM

### ISSUE THREAD

**Issue by janmpeterka** [tomas-dostal/potrebujurousku#37]
## O co jde
Používání Oracle databáze není udržitelné, chceme se přesunout jinam.
Zároveň chceme zlepšit kvalitu kódu.

# Otázky
Chceme MySQL nebo PostgreSQL?
- PostgreSQL je teď hodně populární, ale vlastně se moc neorientuju v jejích výhodách. Jedna, o které vím, je, že podporuje transakce u DDL queries (oproti MySQL).

## Plán
1. Vytvořit lokální databázi na základě schématu té původní.
2. Napojit novou databázi na Django
3. Vygenerovat ORM modely
4. Vytvořit datové import migrace (pro konstantní data)
5. Vytvořit databázovou základní migraci (vytvoření tabulek)
6. Přepsat SQL dotazy do ORM variant.
7. Spustit na serveru

**Comment by tomas-dostal** [comment]
Done ([database-migrate](https://github.com/tomas-dostal/potrebujurousku/tree/database-migrate)):
<s>1) Vytvořit lokální databázi na základě schématu té původní.
2) Napojit novou databázi na Django
3) Vygenerovat ORM modely
4) Vytvořit datové import migrace (pro konstantní data)
5) Vytvořit databázovou základní migraci (vytvoření tabulek)</s>

Zbývá: 
6) Přepsat SQL dotazy do ORM variant
6.1) Poopravit templates, 
7) Spustit na serveru
