### ISSUE TITLE
Konvence psaní kódu a práce s repozitářem

### ISSUE THREAD

**Issue by janpeterka** [tomas-dostal/potrebujurousku#7]
Přijde mi dobrý mít nějaký sdílený konvence psaní kódu a práce s repozitářem.

Já si hodně zvykl pro práci s **kódem** používat následující:
- na formátování [black](https://github.com/psf/black) v kombinaci s [flake8](https://flake8.pycqa.org/en/latest/) linterem
mám to napojené na [pre-commit](https://pre-commit.com) hooks, takže se mi to automaticky kontroluje/formátuje při commitu.
- pak mám ještě [bandit](https://github.com/PyCQA/bandit) na kontrolu bezpečnostních nedostatků.

V **repozitáři** jsem pak zvyklý na následující:
- nový kód přidávat přes **pull requests**, napojené na další automatické kontroly kódu skrz github actions (v public repo jsou zadarmo, tady by asi šlo mít jedině vlastní), a případně se systémem approvals od dalších vývojářů. Přijde mi dobré, aby merge prováděl ten, kdo vytvořil PR.
- do hlavní větve přidávat přímo maximálně nějaké hotfixy, opravy textace.

Taky by mě zajímalo, jestli preferujeme naming český nebo anglický. Teď je to takový mix, tak nevím co mám preferovat, když něco přepisuju.

Ale to jsou jenom moje zvyky, a návrhy rád bych tady vytvořil prostor pro diskuzi :)
A je to asi hlavně na @tomas-dostal jako šéfa :)

**Comment by tomas-dostal** [comment]
Nějaké takové návyky na psaní kódu zatím teprve pěstuji, stejně tak práci s repozitáři. Asi moc nemám jak rozporovat a beru to jako dobrý nápad :) 

Česky-anglicky? Je pravda, že je to mišmaš. Většinou jak mě to zrovna napadlo, tak to šlo. Preferovaný je anglický, když nejsou vhodná slova, tak pak česky...
